name: CI - Build & Push

on:
  push:
    branches:
      - main

env:
  MODULE_NAME: hcl-appointment-service
  ECR_PUBLIC_URI: public.ecr.aws/m7n8t2b8/hcl-appointment-service
  AWS_REGION: us-east-1  # Public ECR is only in us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'SubbuHCL/appointment-service'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and Push Docker Image to Public ECR
        run: |
          docker build -t $MODULE_NAME .
          docker tag $MODULE_NAME $ECR_PUBLIC_URI:${{ github.sha }}
          docker push $ECR_PUBLIC_URI:${{ github.sha }}
